version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: internetBanking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internet_banking_network

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - internet_banking_network

  internet_banking:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: internet_banking_container
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_NAME: internet_banking
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/internet_banking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

    depends_on:
      - postgres
      - redis
    networks:
      - internet_banking_network

volumes:
  postgres_data:

networks:
  internet_banking_network:
    driver: bridge
